wandb_version: 1

_wandb:
  desc: null
  value:
    cli_version: 0.12.14
    framework: torch
    is_jupyter_run: false
    is_kaggle_kernel: false
    python_version: 3.8.16
    start_time: 1684014934
    t:
      1:
      - 1
      - 55
      2:
      - 1
      - 55
      3:
      - 13
      - 16
      4: 3.8.16
      5: 0.12.14
      8:
      - 5
block_size:
  desc: null
  value: 10
context_len_bytes:
  desc: null
  value: 1024
dbg_mode:
  desc: null
  value: 0
dbg_print_context:
  desc: null
  value: 0
dbg_save_audio:
  desc: null
  value: 0
device:
  desc: null
  value: cpu
group_name:
  desc: null
  value: imec-group
imec_belief_entropy_threshold:
  desc: null
  value: 1.0e-09
mec_mode:
  desc: null
  value: dense
medium:
  desc: null
  value: meteor
medium_entropy_loss_threshold:
  desc: null
  value: 0.9
medium_temp:
  desc: null
  value: 0.95
medium_top_k:
  desc: null
  value: 0
message_len_bytes:
  desc: null
  value: 10
message_mode:
  desc: null
  value: randombits
meteor_finish_sent:
  desc: null
  value: false
meteor_is_sort:
  desc: null
  value: 0
meteor_precision:
  desc: null
  value: 0
method:
  desc: null
  value: imec
model_device:
  desc: null
  value: cuda:0
model_name:
  desc: null
  value: gpt2
n_model_procs:
  desc: null
  value: 1
name:
  desc: null
  value: imec_block_10
num_procs:
  desc: null
  value: 1
seed:
  desc: null
  value: 2698319379
stop_after_n_trajectories:
  desc: null
  value: 100
use_arithmetic_coding:
  desc: null
  value: 0
use_chunk_header:
  desc: null
  value: 0
verbose:
  desc: null
  value: 1
wandb_entity:
  desc: null
  value: pt347
wandb_project:
  desc: null
  value: stego_exp
